### ISSUE TITLE
Support Czech language

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify#152]
@vtucan Could you translate it?
https://github.com/PeculiarVentures/fortify/tree/master/locale

**Comment by vtucan** [comment]
I tried my best :)
[cs.json.txt](https://github.com/PeculiarVentures/fortify/files/3042916/cs.json.txt)
Just a comment:

- tag "by" (used in About box) could be "Od společnosti" = "By company". It sounds more Czech than pure "By(Od)" but might be too long
- tag smart.card (and others) - hopefully tags are not combined together in one sentence due to complex declension rules in czech language. All "single word" tags are used in nominative/infinitive which is fine for menus, labels, captions etc

**Comment by microshine** [comment]
@vtucan Thank you very much! I'll add it to the next Fortify update
