### ISSUE TITLE
Could we use Fortify to initialize an USB token?

### ISSUE THREAD

**Issue by antonioaraujob** [PeculiarVentures/fortify#431]
Dear Friends of PeculiarVentures, I hope you are fine.
I have read the information of this URL https://gist.github.com/rmhrisk/d876c155a2266aea81e8d65a6635e94d and it is really good.

<img width="912" alt="Screen Shot 2021-09-05 at 4 11 58 PM" src="https://user-images.githubusercontent.com/8313215/132126420-711e14ad-62de-4d02-b16f-283d10125b08.png">

The architecture and the tools you have developed are excellent. However, I was considering the USB token initialization process.

Could we use PKIjs or Fortify (service) to check if an USB token is already initialized, otherwise initialize it from a browser?

Best regards

Antonio

**Comment by rmhrisk** [comment]
Antonio,

We have not added initialization or unblocking because they are token specific which generally means custom APDUs must be shoved in to accomplish those tasks.

with that said we have considered both and know how we would add them. It would require us to add a non webcrypto API that had different implications per card for those two actions.

for more information contact info@peculiarventires.com.

**Comment by antonioaraujob** [comment]
Dear Ryan, 
Thank you very much for your comments.

I just wanted to know if that was feasible but it seems it requires specific work per card. I will write to get more information.

Best regards

Antonio
